spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:sqlserver://DESKTOP-8RA5OO8\\SQLEXPRESS;databaseName=ecommerce_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=demo_user1
spring.datasource.password=4597@3yuasnm

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

logging.level.org.hibernate.SQL=DEBUG

server.port=8080